// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYp98vZmquF-0ODvAN2mn1t4iamteW8Bg',
    appId: '1:878225414294:web:478b933c7f737d0dce8ab7',
    messagingSenderId: '878225414294',
    projectId: 'notification-db0e2',
    authDomain: 'notification-db0e2.firebaseapp.com',
    storageBucket: 'notification-db0e2.appspot.com',
    measurementId: 'G-LYT7JJ3J9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNhP5R46QRkjC29t5bc4p1dCwnjfbayI',
    appId: '1:878225414294:android:4c314d3b4ecd9ee7ce8ab7',
    messagingSenderId: '878225414294',
    projectId: 'notification-db0e2',
    storageBucket: 'notification-db0e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATJ6xe3ba0ExMF3zrHM3kebuJDFg63IqU',
    appId: '1:878225414294:ios:79fd167f68d12d80ce8ab7',
    messagingSenderId: '878225414294',
    projectId: 'notification-db0e2',
    storageBucket: 'notification-db0e2.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATJ6xe3ba0ExMF3zrHM3kebuJDFg63IqU',
    appId: '1:878225414294:ios:74b6f92b2c6a3cf3ce8ab7',
    messagingSenderId: '878225414294',
    projectId: 'notification-db0e2',
    storageBucket: 'notification-db0e2.appspot.com',
    iosBundleId: 'com.example.untitled4.RunnerTests',
  );
}
